POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlbiIsImlkIjoiNjVmYjAyY2Q5NjhhZmVkMDRmZjJhZjg2IiwiaWF0IjoxNzExMDE1Nzc3fQ.E5UCMlWdR-DEaVRR6LcEoQ0X0KoSmpt9q1Lcctneu-Q
 
    {
        "title": "Traveling the world",
        "author": "John Doe",
        "url": "WWW.johndoe.com",
        "likes": 50
    }