POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhamFsIiwiaWQiOiI2NWZiMDBiNWY5OGU2NmQ2Y2FkNzlhZmUiLCJpYXQiOjE3MTEwMTM0MTB9.I8Xjm_6fbqlU1I7wJzJCF96rfN1J2etQMKtoGwOOdn0
 
    {
        "title": "Read History",
        "author": "Neel Anderson",
        "url": "WWW.books.com",
        "likes": 550
    }